"""Helpers for assembling runIterationPipeline mode-runner dependencies."""

from __future__ import annotations


def buildIterationModeRunnerDependenciesImpl(
    *,
    np_module,
    make_badge_params_fn,
    generate_badge_svg_fn,
    validate_semantic_description_alignment_fn,
    detect_semantic_primitives_fn,
    build_semantic_connector_debug_line_fn,
    build_semantic_mismatch_console_lines_fn,
    build_semantic_mismatch_validation_log_lines_fn,
    build_semantic_mismatch_outcome_fn,
    build_semantic_audit_log_lines_fn,
    build_semantic_audit_record_kwargs_fn,
    semantic_audit_record_fn,
    resolve_semantic_validation_debug_dir_fn,
    collect_semantic_badge_validation_logs_fn,
    validate_badge_by_elements_fn,
    prepare_semantic_badge_post_validation_fn,
    append_semantic_connector_expectation_log_fn,
    build_semantic_ok_validation_outcome_fn,
    build_semantic_ok_validation_log_lines_fn,
    semantic_quality_flags_fn,
    finalize_semantic_badge_run_fn,
    finalize_semantic_badge_iteration_result_fn,
    finalize_ac0223_badge_params_fn,
    render_svg_to_numpy_fn,
    calculate_error_fn,
    enforce_semantic_connector_expectation_fn,
    apply_redraw_variation_fn,
    print_fn,
    run_semantic_badge_iteration_fn,
    detect_dual_arrow_badge_params_fn,
    generate_dual_arrow_badge_svg_fn,
    run_dual_arrow_badge_iteration_fn,
    render_embedded_raster_svg_fn,
    build_gradient_stripe_svg_fn,
    build_gradient_stripe_validation_log_lines_fn,
    run_non_composite_iteration_fn,
    generate_composite_svg_fn,
    create_diff_image_fn,
    run_composite_iteration_fn,
) -> dict[str, object]:
    """Build the dependency mapping consumed by mode runner construction."""

    return {
        "np_module": np_module,
        "make_badge_params_fn": make_badge_params_fn,
        "generate_badge_svg_fn": generate_badge_svg_fn,
        "validate_semantic_description_alignment_fn": validate_semantic_description_alignment_fn,
        "detect_semantic_primitives_fn": detect_semantic_primitives_fn,
        "build_semantic_connector_debug_line_fn": build_semantic_connector_debug_line_fn,
        "build_semantic_mismatch_console_lines_fn": build_semantic_mismatch_console_lines_fn,
        "build_semantic_mismatch_validation_log_lines_fn": build_semantic_mismatch_validation_log_lines_fn,
        "build_semantic_mismatch_outcome_fn": build_semantic_mismatch_outcome_fn,
        "build_semantic_audit_log_lines_fn": build_semantic_audit_log_lines_fn,
        "build_semantic_audit_record_kwargs_fn": build_semantic_audit_record_kwargs_fn,
        "semantic_audit_record_fn": semantic_audit_record_fn,
        "resolve_semantic_validation_debug_dir_fn": resolve_semantic_validation_debug_dir_fn,
        "collect_semantic_badge_validation_logs_fn": collect_semantic_badge_validation_logs_fn,
        "validate_badge_by_elements_fn": validate_badge_by_elements_fn,
        "prepare_semantic_badge_post_validation_fn": prepare_semantic_badge_post_validation_fn,
        "append_semantic_connector_expectation_log_fn": append_semantic_connector_expectation_log_fn,
        "build_semantic_ok_validation_outcome_fn": build_semantic_ok_validation_outcome_fn,
        "build_semantic_ok_validation_log_lines_fn": build_semantic_ok_validation_log_lines_fn,
        "semantic_quality_flags_fn": semantic_quality_flags_fn,
        "finalize_semantic_badge_run_fn": finalize_semantic_badge_run_fn,
        "finalize_semantic_badge_iteration_result_fn": finalize_semantic_badge_iteration_result_fn,
        "finalize_ac0223_badge_params_fn": finalize_ac0223_badge_params_fn,
        "render_svg_to_numpy_fn": render_svg_to_numpy_fn,
        "calculate_error_fn": calculate_error_fn,
        "enforce_semantic_connector_expectation_fn": enforce_semantic_connector_expectation_fn,
        "apply_redraw_variation_fn": apply_redraw_variation_fn,
        "print_fn": print_fn,
        "run_semantic_badge_iteration_fn": run_semantic_badge_iteration_fn,
        "detect_dual_arrow_badge_params_fn": detect_dual_arrow_badge_params_fn,
        "generate_dual_arrow_badge_svg_fn": generate_dual_arrow_badge_svg_fn,
        "run_dual_arrow_badge_iteration_fn": run_dual_arrow_badge_iteration_fn,
        "render_embedded_raster_svg_fn": render_embedded_raster_svg_fn,
        "build_gradient_stripe_svg_fn": build_gradient_stripe_svg_fn,
        "build_gradient_stripe_validation_log_lines_fn": build_gradient_stripe_validation_log_lines_fn,
        "run_non_composite_iteration_fn": run_non_composite_iteration_fn,
        "generate_composite_svg_fn": generate_composite_svg_fn,
        "create_diff_image_fn": create_diff_image_fn,
        "run_composite_iteration_fn": run_composite_iteration_fn,
    }
