"""Auto-generated loader for split module chunks.

DO NOT EDIT MANUALLY. Re-run tools/split_python_module.py instead.
"""

from __future__ import annotations

from pathlib import Path

_BASE_DIR = Path(__file__).resolve().parent
_CHUNK_DIR = _BASE_DIR / 'image_composite_converter_chunks'
_CHUNK_FILES = [
    "image_composite_converter.chunk_0001.py",
    "image_composite_converter.chunk_0002.py",
    "image_composite_converter.chunk_0003.py",
    "image_composite_converter.chunk_0004.py",
    "image_composite_converter.chunk_0005.py",
    "image_composite_converter.chunk_0006.py",
    "image_composite_converter.chunk_0007.py",
    "image_composite_converter.chunk_0008.py",
    "image_composite_converter.chunk_0009.py",
    "image_composite_converter.chunk_0010.py",
    "image_composite_converter.chunk_0011.py",
    "image_composite_converter.chunk_0012.py",
    "image_composite_converter.chunk_0013.py",
    "image_composite_converter.chunk_0014.py",
    "image_composite_converter.chunk_0015.py",
    "image_composite_converter.chunk_0016.py",
    "image_composite_converter.chunk_0017.py",
    "image_composite_converter.chunk_0018.py",
    "image_composite_converter.chunk_0019.py",
    "image_composite_converter.chunk_0020.py",
    "image_composite_converter.chunk_0021.py",
    "image_composite_converter.chunk_0022.py",
    "image_composite_converter.chunk_0023.py",
    "image_composite_converter.chunk_0024.py",
    "image_composite_converter.chunk_0025.py",
    "image_composite_converter.chunk_0026.py",
    "image_composite_converter.chunk_0027.py",
    "image_composite_converter.chunk_0028.py",
    "image_composite_converter.chunk_0029.py",
    "image_composite_converter.chunk_0030.py",
    "image_composite_converter.chunk_0031.py",
    "image_composite_converter.chunk_0032.py",
    "image_composite_converter.chunk_0033.py",
    "image_composite_converter.chunk_0034.py",
    "image_composite_converter.chunk_0035.py",
    "image_composite_converter.chunk_0036.py",
    "image_composite_converter.chunk_0037.py",
    "image_composite_converter.chunk_0038.py",
    "image_composite_converter.chunk_0039.py",
    "image_composite_converter.chunk_0040.py",
    "image_composite_converter.chunk_0041.py",
    "image_composite_converter.chunk_0042.py",
    "image_composite_converter.chunk_0043.py",
    "image_composite_converter.chunk_0044.py",
    "image_composite_converter.chunk_0045.py",
    "image_composite_converter.chunk_0046.py",
    "image_composite_converter.chunk_0047.py",
    "image_composite_converter.chunk_0048.py",
    "image_composite_converter.chunk_0049.py",
    "image_composite_converter.chunk_0050.py",
    "image_composite_converter.chunk_0051.py",
    "image_composite_converter.chunk_0052.py",
    "image_composite_converter.chunk_0053.py",
    "image_composite_converter.chunk_0054.py",
    "image_composite_converter.chunk_0055.py",
    "image_composite_converter.chunk_0056.py",
    "image_composite_converter.chunk_0057.py",
    "image_composite_converter.chunk_0058.py",
    "image_composite_converter.chunk_0059.py",
    "image_composite_converter.chunk_0060.py",
    "image_composite_converter.chunk_0061.py",
    "image_composite_converter.chunk_0062.py",
    "image_composite_converter.chunk_0063.py",
    "image_composite_converter.chunk_0064.py",
    "image_composite_converter.chunk_0065.py",
    "image_composite_converter.chunk_0066.py",
    "image_composite_converter.chunk_0067.py",
    "image_composite_converter.chunk_0068.py",
    "image_composite_converter.chunk_0069.py",
    "image_composite_converter.chunk_0070.py",
    "image_composite_converter.chunk_0071.py",
    "image_composite_converter.chunk_0072.py",
    "image_composite_converter.chunk_0073.py",
    "image_composite_converter.chunk_0074.py",
    "image_composite_converter.chunk_0075.py",
    "image_composite_converter.chunk_0076.py",
    "image_composite_converter.chunk_0077.py",
    "image_composite_converter.chunk_0078.py",
    "image_composite_converter.chunk_0079.py",
    "image_composite_converter.chunk_0080.py",
    "image_composite_converter.chunk_0081.py",
    "image_composite_converter.chunk_0082.py",
    "image_composite_converter.chunk_0083.py",
    "image_composite_converter.chunk_0084.py",
    "image_composite_converter.chunk_0085.py",
    "image_composite_converter.chunk_0086.py",
    "image_composite_converter.chunk_0087.py",
    "image_composite_converter.chunk_0088.py",
    "image_composite_converter.chunk_0089.py",
    "image_composite_converter.chunk_0090.py",
    "image_composite_converter.chunk_0091.py",
    "image_composite_converter.chunk_0092.py",
    "image_composite_converter.chunk_0093.py",
    "image_composite_converter.chunk_0094.py",
    "image_composite_converter.chunk_0095.py",
    "image_composite_converter.chunk_0096.py",
    "image_composite_converter.chunk_0097.py",
    "image_composite_converter.chunk_0098.py",
    "image_composite_converter.chunk_0099.py",
    "image_composite_converter.chunk_0100.py",
    "image_composite_converter.chunk_0101.py",
    "image_composite_converter.chunk_0102.py",
    "image_composite_converter.chunk_0103.py",
    "image_composite_converter.chunk_0104.py",
    "image_composite_converter.chunk_0105.py",
    "image_composite_converter.chunk_0106.py",
    "image_composite_converter.chunk_0107.py",
    "image_composite_converter.chunk_0108.py",
    "image_composite_converter.chunk_0109.py",
    "image_composite_converter.chunk_0110.py",
    "image_composite_converter.chunk_0111.py",
    "image_composite_converter.chunk_0112.py",
    "image_composite_converter.chunk_0113.py",
    "image_composite_converter.chunk_0114.py",
    "image_composite_converter.chunk_0115.py",
    "image_composite_converter.chunk_0116.py",
    "image_composite_converter.chunk_0117.py",
    "image_composite_converter.chunk_0118.py",
    "image_composite_converter.chunk_0119.py",
    "image_composite_converter.chunk_0120.py",
]

_source_parts: list[str] = []
for _chunk_file in _CHUNK_FILES:
    _source_parts.append((_CHUNK_DIR / _chunk_file).read_text(encoding="utf-8"))

_COMBINED_SOURCE = "".join(_source_parts)
exec(compile(_COMBINED_SOURCE, 'image_composite_converter.py', "exec"), globals(), globals())
